import type { Metadata } from 'next';
import { Public_Sans } from 'next/font/google';
import React from 'react';
import './custom.variables.css';

const publicSans = Public_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800'],
  fallback: ['sistem-ui', 'arial'],
});

export const metadata: Metadata = {
  title: 'Easybank',
  description: 'Generated by create next app',

};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={publicSans.className}>
    {children}

    </body>
    </html>
  );
}
